### PR TITLE
ExeUnits & Runtimes

### PR DESCRIPTION
**Pull request by kamirr**
This change is [Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/116)

### CODE REVIEW

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/116)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @kamirr)

___
*[`arch-snapshot/arch.md` line 579 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9z8Z49B_WuXkrqpNAZ:-O9z8Z49B_WuXkrqpNA_:bbxuegn) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L579)):*
Can you please emphasize that there are different ExeUnits?
E.g.
> Different Activities require different ExeUnits, hence multiple implementations providing support for different kinds of Activities.



_Code quote:_
```Markdown
Abstractly speaking, ExeUnit performs work on behalf of the Requestor utilizing
Provider's resources. What this work pertains to is part of the Agreement
negotiated by the Provider and Requestor.
```
___
*[`arch-snapshot/arch.md` line 624 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9z9EzqDxC0p6kl82bV:-O9z9EzqDxC0p6kl82bW:bk0ae3o) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L624)):*
> ```Markdown
> - WASM – [TODO: Never worked on it]. See (WASM runtime)(#WASM-Runtime).
> 
>  SGX – [TODO: Removal approved by reqc but not merged yet, should we document?]
> ```

Feel free to remove from the document.



_Code quote:_
```Markdown
 SGX – [TODO: Removal approved by reqc but not merged yet, should we document?]
```
___
*[`arch-snapshot/arch.md` line 629 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9z9hOwEFBtN83nAFSD:-O9z9hOwEFBtN83nAFSE:b9wjs3) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L629)):*
> ```Markdown
> Some ExeUnits with much narrower applicability have been developed over
> time.
> - AI Evaluation ExeUnit designed for GamerHash –
> ```

I think it's called "AI inference"



_Code quote:_
```Markdown
AI Evaluation 
```
___
*[`arch-snapshot/arch.md` line 642 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zA8o09mlwVkUyGLKq:-O9zA8o09mlwVkUyGLKr:b-q0cy6e) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L642)):*
> ```Markdown
> ExeUnits are controlled by the Golem Node using GSB, the same message-passing
> protocol that is used for internal implementation of the Node as well as
> inter-node communication.
> ```

I don't understand it. What communication is internal? And why would a Node speak to another Node (internode) to with ExeUnit-specific messages?



_Code quote:_
```Markdown
protocol that is used for internal implementation of the Node as well as
inter-node communication.
```
___
*[`arch-snapshot/arch.md` line 667 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zBMRG4gcm5zAmHoT_:-O9zBMRG4gcm5zAmHoTa:bmbox05) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L667)):*
> ```Markdown
> [gftp implementation](https://github.com/golemfactory/yagna/tree/master/core/gftp).
> 
> Additionally, some endpoints are exposed directly to the Requestor Agent,
> ```

These are GDB endpoint, right?



_Code quote:_
```Markdown
endpoints
```
___
*[`arch-snapshot/arch.md` line 676 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zBWjL3RScLXb8KCaW:-O9zBWjL3RScLXb8KCaX:b-8744ca) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L676)):*
> ```Markdown
> #### ExeUnit Commands
> The Requestor Agent does not control the ExeUnit by GSB, but by using
> a dedicated REST API that maps user-friendly messages to the `Exec` GSB message
> ```

eposed by their Yagna, right? Also, perhaps it's worth mentioning that the SDKs also wrap it in idiomatic libraries.



_Code quote:_
```Markdown
 REST API
```
___
*[`arch-snapshot/arch.md` line 714 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zC5tRCz6IagnoAixb:-O9zC5tRCz6IagnoAixc:b505d8f) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L714)):*
> ```Markdown
> #### ExeUnit Runtime
> The Runtime models specific kind of computation compatible with the ExeUnit
> Supervisor.
> ```

I'm sorry, but I don't understand this. What is abstracted and how? If this is just a code-structure thing then I think we can safely skip these sections.



_Code quote:_
```Markdown
#### ExeUnit Supervisor
The Supervisor abstracts over common components of ExeUnits to allow easier
development of new computation modes – one only needs to implement the
[ExeUnit Runtime](#ExeUnit-Runtime).

#### ExeUnit Runtime
The Runtime models specific kind of computation compatible with the ExeUnit
Supervisor.
```
___
*[`arch-snapshot/arch.md` line 731 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zCLQU4_1lDTspf_HD:-O9zCLQVD3nl1C-kxBKm:b-abnzng) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L731)):*
> ```Markdown
>     standard error as well as the return code of the process.
> - The images for the VM are built via gvmkit-build from a Dockerfile-like
>   format to lower the steepness of the learning curve.
> ```

We need way more information here. Moreover, I'm sure that my list is not exhaustive so I nee your judgement to describe the missing pieces, too:
* A little bit more about the virtualization. This is qemu with kvm, right?
* How do we ensure that the VM gets the promised resources?
* Are we limiting the VM to not use more resources than what the Agreement states?
* How does storage work, i.e.:
  * how are the images constructed
  * how are they "mounted" into the VM
  * there is no persistence between runs, right?
* How do we control the VM kernel (the Golem's own `init` process with an RPC to the host OS)
* How does network work?



_Code quote:_
```Markdown
- Operates by running code within a virtual machine, which prevents malicious
  code submitted by the Requestor from negatively impacting the machine on which
  the Provider Agent runs.
- Functionalities:
  - Outbound allows communicating with the internet via a virtual network
    interface that filters network traffic according to Provider's configuration
    as means of protection against illegal activities to the Provider.
  - VPN is also implemented using a virtual network interface so that various
    instances of the Runtime (from different Activities and possibly Providers)
    and the Requestor Agent can communicate using conventional networking
    solutions.
  - Process output capture allows the Requestor Agent to obtain standard output,
    standard error as well as the return code of the process.
- The images for the VM are built via gvmkit-build from a Dockerfile-like
  format to lower the steepness of the learning curve.
```

**Review by kamirr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/116)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 579 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9z8Z49B_WuXkrqpNAZ:-OAGphyK9qS-ZqwxBbcx:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L579)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can you please emphasize that there are different ExeUnits?
E.g.
> Different Activities require different ExeUnits, hence multiple implementations providing support for different kinds of Activities.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 624 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9z9EzqDxC0p6kl82bV:-OAGpm0VEhV8VJ_Iva3J:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L624)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Feel free to remove from the document.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 629 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9z9hOwEFBtN83nAFSD:-OAGpmlUCFdSzceEgpO3:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L629)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think it's called "AI inference"
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 642 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zA8o09mlwVkUyGLKq:-OAGqAn10bWX85YP8zBV:b-jfb1b7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L642)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't understand it. What communication is internal? And why would a Node speak to another Node (internode) to with ExeUnit-specific messages?
</blockquote></details>

I don't understand where the confusion stems from, right before your quote it says `ExeUnits are controlled by the Golem Node using GSB, the same message-passing`, meaning the quoted section doesn't refer to ExeUnit but quickly recaps what GSB is.
___
*[`arch-snapshot/arch.md` line 667 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zBMRG4gcm5zAmHoT_:-OAGqeaD03LXB1kmOvBl:b3aox3t) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L667)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

These are GDB endpoint, right?
</blockquote></details>

You mean GSB, right? Yes, and I've made it explicit in the doc
___
*[`arch-snapshot/arch.md` line 676 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zBWjL3RScLXb8KCaW:-OAGrIuN4tL21AznfPfQ:bba2gw2) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L676)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

eposed by their Yagna, right? Also, perhaps it's worth mentioning that the SDKs also wrap it in idiomatic libraries.
</blockquote></details>

I've clarified that yagna exposes the REST API. The second point is actually not exactly true, because the content of ExeUnit commands depends on the ExeUnit, which means we can't enforce it with our OpenAPI spec. What we have there is a reference design (matching our VM runtime) but it's not tied to the endpoint -- instead we just take untyped objects.
___
*[`arch-snapshot/arch.md` line 714 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zC5tRCz6IagnoAixb:-OAGsN5wC9PjYJCwOvPp:be9cj8w) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L714)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'm sorry, but I don't understand this. What is abstracted and how? If this is just a code-structure thing then I think we can safely skip these sections.
</blockquote></details>

I guess it's only code structure. Removed.
___
*[`arch-snapshot/arch.md` line 731 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zCLQU4_1lDTspf_HD:-OAGsjljA99NGmgQpkmW:b-psr0xc) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L731)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

We need way more information here. Moreover, I'm sure that my list is not exhaustive so I nee your judgement to describe the missing pieces, too:
* A little bit more about the virtualization. This is qemu with kvm, right?
* How do we ensure that the VM gets the promised resources?
* Are we limiting the VM to not use more resources than what the Agreement states?
* How does storage work, i.e.:
  * how are the images constructed
  * how are they "mounted" into the VM
  * there is no persistence between runs, right?
* How do we control the VM kernel (the Golem's own `init` process with an RPC to the host OS)
* How does network work?
</blockquote></details>

Before I made this patch it said `Virtual machine desciption (so the reader knows what is there, but not details)`. I can elaborate on `How does network work?` but it's a deep rabbit hole. Is there a specific level of detail you have in mind?

Otherwise done

**Review by dopiera — COMMENTED** [review]
Looks good, just one more thing please.

> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-:-OAW8xOh2SGr3-FJ4byT:b1ked9v)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kamirr)

___
*[`arch-snapshot/arch.md` line 731 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zCLQU4_1lDTspf_HD:-OAW8RUCA8CNydMYZiZy:brcyrl0) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L731)):*
<details><summary><i>Previously, kamirr (Kamil Koczurek) wrote…</i></summary><blockquote>

Before I made this patch it said `Virtual machine desciption (so the reader knows what is there, but not details)`. I can elaborate on `How does network work?` but it's a deep rabbit hole. Is there a specific level of detail you have in mind?

Otherwise done
</blockquote></details>

I think the cut-off level is good, except the network. Similarly to controlling the `init` process - please feel free to just move the content from #114 here and adapt it to describe how outbound works.
___
*[`arch-snapshot/arch.md` line 719 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-OAW7f8pDEl0MlQ08mQP:-OAW7f8pDEl0MlQ08mQQ:bw6g8tj) ([raw file](https://github.com/golemfactory/golem-architecture/blob/595193cf39ee588d80fa676af17bab0798fc306d/arch-snapshot/arch.md#L719)):*
> ```Markdown
>   - The VM is controlled from the outside by passing messages to the init
>     process. This is necessary for implementing the functionalities below this
>     point. 
> ```

From the description, it's unclear how. Feel free to steal the stuff from #114 (https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nVfnx4EUvu8Ua7W3_ ) - I think Witek is right that it belongs here.



_Code quote:_
```Markdown
  - The VM is controlled from the outside by passing messages to the init
    process. This is necessary for implementing the functionalities below this
    point.
```

**Review by kamirr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/116)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 731 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-O9zCLQU4_1lDTspf_HD:-OAXT1HS5Ob5nDvu271Z:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/31958adb0f275d1ff9f998e330955a9e9ad91362/arch-snapshot/arch.md#L731)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think the cut-off level is good, except the network. Similarly to controlling the `init` process - please feel free to just move the content from #114 here and adapt it to describe how outbound works.
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 719 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/116#-OAW7f8pDEl0MlQ08mQP:-OAXT0Tc8KZ_iFXFReij:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/595193cf39ee588d80fa676af17bab0798fc306d/arch-snapshot/arch.md#L719)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

From the description, it's unclear how. Feel free to steal the stuff from #114 (https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nVfnx4EUvu8Ua7W3_ ) - I think Witek is right that it belongs here.
</blockquote></details>

Done

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/116)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @kamirr)

**Pull request merged**
