### PR TITLE
Add Deployment documentation to architecture snapshot

### PR DESCRIPTION
**Pull request by kamirr**
This change is [Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)

### CODE REVIEW

**Review by nieznanysprawiciel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kamirr)

___
*[`arch-snapshot/arch.md` line 2389 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLX1z9XUhMfyoo7wW:-OArLX1z9XUhMfyoo7wX:bsra253) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2389)):*
> ```Markdown
>   * Identity
>   * Networking
>   * GSB
> ```

I think we don't treat GSB as separate component but a way to communicate between components
___
*[`arch-snapshot/arch.md` line 2393 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLkn48C2HWnr_o8YL:-OArLkn48C2HWnr_o8YM:b-4wao7a) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2393)):*
> ```Markdown
>   * Payments
>     * Payment Drivers
> * Requestor Agent is a separate process, usually implemented using an SDK
> ```

Do we describe anywhere how do you build an requestor, what is it and what are the interactions?
If yes than please link it, if not it should be described
___
*[`arch-snapshot/arch.md` line 2418 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArKZRO6U-aScM7jKRo:-OArKZRO6U-aScM7jKRp:b-z58i8i) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2418)):*
> ```Markdown
>     - QEMU if Activity is deployed and using VM Runtime.
>     - Wasmtime if Activity is deployed and using WASM Runtime.
> #### Requestor & Provider
> ```

I don't understand this chapter. Either it is obvious setup or it should be structured differently.
For example if you want to say that you can have setup where provider and requestor use the same yagna, you should say that this is an option. I wouldn't just list processes and force reader to guess.

**Review by nieznanysprawiciel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dopiera and @kamirr)

___
*[`arch-snapshot/arch.md` line 2414 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArRBPf2jmwQBdDOlcL:-OArRBPf2jmwQBdDOlcM:bz1lsiq) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2414)):*
> ```Markdown
> - Provider Agent
> - Per Activity:
>   - ExeUnit
> ```

It isn't clear if ExeUnit is separate binary or you describe subcomponents

**Review by nieznanysprawiciel — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera and @kamirr)

___
*[`arch-snapshot/arch.md` line 2413 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArSwW980xzDjGwXV9c:-OArSwW980xzDjGwXV9d:b-dr297y) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2413)):*
> ```Markdown
> - Yagna
> - Provider Agent
> - Per Activity:
> ```

Will it be understandable for reader in this part of document?

**Review by kamirr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera and @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 2389 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLX1z9XUhMfyoo7wW:-OArb8UH8fiTYTrwf0WS:b-oucj60) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2389)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I think we don't treat GSB as separate component but a way to communicate between components
</blockquote></details>

Well there is the router that's which is sensible to be treated as a component. It was also listed under components in the document, and I wanted to keep it consistent.
___
*[`arch-snapshot/arch.md` line 2393 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLkn48C2HWnr_o8YL:-OArcxMdCvWB6ZxRbClD:b-bv19pq) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2393)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Do we describe anywhere how do you build an requestor, what is it and what are the interactions?
If yes than please link it, if not it should be described
</blockquote></details>

I don't really think a complete instruction to building Providers and Requestors should be in this document. We have plenty tutorials, and this isn't exactky what I'd call `architecture`.

@dopiera what do you think?
___
*[`arch-snapshot/arch.md` line 2413 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArSwW980xzDjGwXV9c:-OArbh0cBEd08fxwnRxo:b-t1lxfd) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2413)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Will it be understandable for reader in this part of document?
</blockquote></details>

I've reworded it to be more verbose, but otherwise assumed that a user reading about specifics of a deployment should be familiar with activities.
___
*[`arch-snapshot/arch.md` line 2414 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArRBPf2jmwQBdDOlcL:-OArbs76ERtcd437B-C5:br2mxqe) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2414)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

It isn't clear if ExeUnit is separate binary or you describe subcomponents
</blockquote></details>

It's explicitly said that those are process trees, I didn't want to pollute it with explaining that something is a process.
___
*[`arch-snapshot/arch.md` line 2418 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArKZRO6U-aScM7jKRo:-OArcj088NnWs95rmelp:b-grlq8x) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2418)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I don't understand this chapter. Either it is obvious setup or it should be structured differently.
For example if you want to say that you can have setup where provider and requestor use the same yagna, you should say that this is an option. I wouldn't just list processes and force reader to guess.
</blockquote></details>

Right, I added this for symmetry but I agree that it's somewhat confusing. Removed.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kamirr and @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 2389 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLX1z9XUhMfyoo7wW:-OAt9LPWAoDxwpXHNMUh:bsqto1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2389)):*
<details><summary><i>Previously, kamirr (Kamil Koczurek) wrote…</i></summary><blockquote>

Well there is the router that's which is sensible to be treated as a component. It was also listed under components in the document, and I wanted to keep it consistent.
</blockquote></details>

+1 to @nieznanysprawiciel 
___
*[`arch-snapshot/arch.md` line 2393 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLkn48C2HWnr_o8YL:-OAtAWJ2EcYjLg8Dj1Tv:b-fjup7) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2393)):*
<details><summary><i>Previously, kamirr (Kamil Koczurek) wrote…</i></summary><blockquote>

I don't really think a complete instruction to building Providers and Requestors should be in this document. We have plenty tutorials, and this isn't exactky what I'd call `architecture`.

@dopiera what do you think?
</blockquote></details>

+1 @kamirr - even though I find it beneficial I'm afraid we need to limit the scope of this document.
___
*[`arch-snapshot/arch.md` line 2380 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OAt8CbQ5F6_CxOXUNw3:-OAt8CbQ5F6_CxOXUNw4:b9qjc6l) ([raw file](https://github.com/golemfactory/golem-architecture/blob/6aa96dd5587a906d964b63e6e0b83252614c0ca9/arch-snapshot/arch.md#L2380)):*
> ```Markdown
> * which of the logic useful to the user ends up in the SDK
> 
> ## Technical view - deployment
> ```

Can we please start with some explanation of how we split the responsibilities? Feel free to refer to #109 (still unmerged). E.g. something along these lines:

Golem, as described in the [layers section](#layers), stack functionalities on top of each other. As a consequence, typically there are following processes involved:
* Yagna - the process which implements the [core network](#core-network), i.e. the ability for nodes to find each other and trade
* Provider - ...
* Requestor Agent - 
* ...

Only after you do that, please assign the components to those processes.



_Code quote:_
```Markdown
## Technical view - deployment
```

**Review by kamirr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dopiera and @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 2389 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLX1z9XUhMfyoo7wW:-OAw8OJW2JIU11xGh_kT:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2389)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

+1 to @nieznanysprawiciel
</blockquote></details>

Done
___
*[`arch-snapshot/arch.md` line 2393 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OArLkn48C2HWnr_o8YL:-OAw8Pt5EIPXImARdmB1:b2nhb2c) ([raw file](https://github.com/golemfactory/golem-architecture/blob/910edd61cc3f3ce35405faf5b2cfaca4380bffc0/arch-snapshot/arch.md#L2393)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

+1 @kamirr - even though I find it beneficial I'm afraid we need to limit the scope of this document.
</blockquote></details>

Ack
___
*[`arch-snapshot/arch.md` line 2380 at r2](https://reviewable.io/reviews/golemfactory/golem-architecture/121#-OAt8CbQ5F6_CxOXUNw3:-OAw8NeRAGzIwcksJ1QK:bb6un1j) ([raw file](https://github.com/golemfactory/golem-architecture/blob/6aa96dd5587a906d964b63e6e0b83252614c0ca9/arch-snapshot/arch.md#L2380)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can we please start with some explanation of how we split the responsibilities? Feel free to refer to #109 (still unmerged). E.g. something along these lines:

Golem, as described in the [layers section](#layers), stack functionalities on top of each other. As a consequence, typically there are following processes involved:
* Yagna - the process which implements the [core network](#core-network), i.e. the ability for nodes to find each other and trade
* Provider - ...
* Requestor Agent - 
* ...

Only after you do that, please assign the components to those processes.
</blockquote></details>

Done

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/121)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @nieznanysprawiciel)

**Pull request merged**
