### PR TITLE
feat: describe the VPN

### PR DESCRIPTION
**Pull request by dopiera**
- - -
This change is [Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)

### CODE REVIEW

**Review by nieznanysprawiciel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 650 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nr-S83CmAxpO74OKi:-O9nr-S83CmAxpO74OKj:b-elmphn) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L650)):*
> ```Markdown
> - WASM images
> 
> ### VPN
> ```

I think this chapter lacks description how Requestor interacts with VPN.
And it is very cumbersome in current implementation, since he can't just use normal network interface.
SDK needs to make strange things like implementing proxy that talks with yagna through WebSocket. It looks like something to improve
___
*[`arch-snapshot/arch.md` line 656 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nXe4X5aRNeybf7jhu:-O9nXe4X5aRNeybf7jhv:b-qb7t4i) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L656)):*
> ```Markdown
> This component provides that functionality.
> 
> The VPN operates as a typical layer 3 VPN and was designed to meet the following
> ```

I'm not sure about this.
From technical perspective VPN works on Ethernet frames levels. This is only due to smoltcp stack being not able to work on IP layer (and newer version can), and I would be glad to change that, but this makes this sentence problematic.

But we could say that this implementation and functionally our VPN behaves like layer 3 VPN.
But this would be problematic as well. From VM perspective it looks like this. But from Requestor perspective you can't use VPN in transparent way. For Requestor it would be rather application layer of OSI model or something like that.



_Code quote:_
```Markdown
typical layer 3 VPN
```
___
*[`arch-snapshot/arch.md` line 677 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nndhV-B4GSUjjMQcj:-O9nndhV-B4GSUjjMQck:bc73jvw) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L677)):*
> ```Markdown
> 2. The hypervisor forwards traffic to/from the virtualized Ethernet device to
>    ExeUnit running on the host OS.
> 3. The ExeUnit tunnels traffic to/from other ExeUnits responsible for different
> ```

Somewhere should be mentioned that VPN packets are tunneled through GSB. This is potentially problematic, because of additional operations that needs to be performed and may potentially lead to worse performance.
___
*[`arch-snapshot/arch.md` line 683 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nruS88LSHz0gEpS09:-O9nruS88LSHz0gEpS0A:b-rmh5y2) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L683)):*
> ```Markdown
> 
> The guest VM is run using [qemu](https://www.qemu.org/). Qemu offers the
> `-netdev socket` option, which creates a virtual Ethernet device in the guest OS
> ```

It looks like very quemu specific thing. I would create separate chapters about VM examples
___
*[`arch-snapshot/arch.md` line 704 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nUd-s5_Mwlk6HiJ56:-O9nUd-s5_Mwlk6HiJ57:boq6anf) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L704)):*
> ```Markdown
> fulfilled:
> 
> - Every VM, along with the Requestor (which is always part of the VPN), must be
> ```

Requestor creates the network, but he doesn't have to assign IP address to himself, so doesn't have to be part of the VPN network. Providers could talk only between themselves.
___
*[`arch-snapshot/arch.md` line 727 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nVfnx4EUvu8Ua7W3_:-O9nVfnx4EUvu8Ua7W3a:b-4nlsm6) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L727)):*
> ```Markdown
> OS. This is achieved via qemu’s `-chardev` argument, which emulates a character
> device in the guest VM. Essentially, this device acts as a bidirectional pipe
> to a designated UNIX socket on the host OS. This mechanism facilitates an RPC
> ```

This looks like part of VM description. Here could be mentioning that there is a communication channel and link to description in ExeUnit Supervisor and VMs.
Controlling VPN is only one aspect of the interface for controlling ExeUnit Runtimes.

In general I would organize VPN description into part about generic mechanisms and examples or specifics about VM implementation

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 650 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nr-S83CmAxpO74OKi:-O9ytmTp6uL37WoUYT53:boe53tc) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L650)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I think this chapter lacks description how Requestor interacts with VPN.
And it is very cumbersome in current implementation, since he can't just use normal network interface.
SDK needs to make strange things like implementing proxy that talks with yagna through WebSocket. It looks like something to improve
</blockquote></details>

Added, PTAL.
___
*[`arch-snapshot/arch.md` line 656 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nXe4X5aRNeybf7jhu:-O9xeH2iDvIi-50T6DgN:b-118mke) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L656)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I'm not sure about this.
From technical perspective VPN works on Ethernet frames levels. This is only due to smoltcp stack being not able to work on IP layer (and newer version can), and I would be glad to change that, but this makes this sentence problematic.

But we could say that this implementation and functionally our VPN behaves like layer 3 VPN.
But this would be problematic as well. From VM perspective it looks like this. But from Requestor perspective you can't use VPN in transparent way. For Requestor it would be rather application layer of OSI model or something like that.
</blockquote></details>

Here's the reasoning behind my conclusion:
- The VPN only tunnels IP packets and a only a narrow subset of ARP packets (only those necessary for IP communication). (https://github.com/golemfactory/yagna/blob/3d584097a0b2759d0184d9e89ea0756db1779bbb/exe-unit/src/network/vpn.rs#L285)
  - This suggests it does not operate at Layer 2.
- Since it can tunnel any IP packet, this points to Layer 3 functionality.

Additionally, the VPN appears to use IP addresses for routing rather than MAC addresses for switching, which further supports the idea that it's working at Layer 3.

While I understand that we're forwarding entire Ethernet frames, this seems to be more of an implementation convenience rather than a core indication of Layer 2 functionality. For instance, in the [ya-runtime-vm example](https://github.com/golemfactory/ya-runtime-vm/blob/master/runtime/examples/network.rs), the MAC addresses are synthesized, indicating they aren't critical from the VPN's perspective.

Regarding the suggestion of a higher-level OSI model: I’m curious why a client implementation (i.e., the Requestor) would influence the classification of this VPN. The [ya-vpn-connector](https://github.com/golemfactory/ya-vpn-connector) exposes a network interface and uses TUN, which is Layer 3. BTW it also synthesizes MAC addresses.
___
*[`arch-snapshot/arch.md` line 677 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nndhV-B4GSUjjMQcj:-O9yAJn--0Fp63-l6a8T:b-hmgmr8) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L677)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Somewhere should be mentioned that VPN packets are tunneled through GSB. This is potentially problematic, because of additional operations that needs to be performed and may potentially lead to worse performance.
</blockquote></details>

Added below
___
*[`arch-snapshot/arch.md` line 683 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nruS88LSHz0gEpS09:-O9yssAC3wkMHiKDutsC:b-sj60zy) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L683)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

It looks like very quemu specific thing. I would create separate chapters about VM examples
</blockquote></details>

It is indeed. I've moved the VM-specific stuff to the end of the section.

Given that the VPN makes no sense without the VMs, I'm not sure what meaningful generalization there if VMs are too specific.
___
*[`arch-snapshot/arch.md` line 704 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nUd-s5_Mwlk6HiJ56:-O9y9pRj-Tvn241KTFk6:b-7ql1td) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L704)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

Requestor creates the network, but he doesn't have to assign IP address to himself, so doesn't have to be part of the VPN network. Providers could talk only between themselves.
</blockquote></details>

fixed
___
*[`arch-snapshot/arch.md` line 727 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nVfnx4EUvu8Ua7W3_:-O9y9OyV66qf9cm8udkS:b-hll1yk) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L727)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

This looks like part of VM description. Here could be mentioning that there is a communication channel and link to description in ExeUnit Supervisor and VMs.
Controlling VPN is only one aspect of the interface for controlling ExeUnit Runtimes.

In general I would organize VPN description into part about generic mechanisms and examples or specifics about VM implementation
</blockquote></details>

This is a good point, let me rebase this on top of #116 in order to ensure that what I want to link to is available. EDIT - this has not yet been described - keeping this comment open until it is.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @dopiera and @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 727 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nVfnx4EUvu8Ua7W3_:-OAo6Dcl6E4bMbwI7Lug:b5p4afm) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L727)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This is a good point, let me rebase this on top of #116 in order to ensure that what I want to link to is available. EDIT - this has not yet been described - keeping this comment open until it is.
</blockquote></details>

Fixed, PTAL

**Review by nieznanysprawiciel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 683 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nruS88LSHz0gEpS09:-OAqeqpX1VviuaOEfECP:b-jm5bcr) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L683)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It is indeed. I've moved the VM-specific stuff to the end of the section.

Given that the VPN makes no sense without the VMs, I'm not sure what meaningful generalization there if VMs are too specific.
</blockquote></details>

For example outbound-gateway: https://github.com/golemfactory/ya-runtime-outbound-gateway which was used in prototype of VPN routing traffic through golem nodes
___
*[`arch-snapshot/arch.md` line 2374 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-OAqg_nG67ExcGi4uBsM:-OAqg_nG67ExcGi4uBsN:b-jxnzao) ([raw file](https://github.com/golemfactory/golem-architecture/blob/77fac8d33c07fad295bb2e32a48639bbc56e9e6a/arch-snapshot/arch.md#L2374)):*
> ```Markdown
> 
> The VM runtime allows Requestors to spin up virtual machines (VMs). To enable
> these VMs to act as a cluster, a VPN is essential for securely connecting them.
> ```

I forgot to comment earlier: `securely` can be misleading. VPN doesn't encrypt traffic by itself. It relies on networking layer to do it. And currently there is no encryption.
___
*[`arch-snapshot/arch.md` line 2450 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-OAqhbdA7F0eGtEg44DE:-OAqhbdA7F0eGtEg44DF:b-p866l9) ([raw file](https://github.com/golemfactory/golem-architecture/blob/77fac8d33c07fad295bb2e32a48639bbc56e9e6a/arch-snapshot/arch.md#L2450)):*
> unreliable channels
I changed terminology to transport type.
But I think you can leave it as is.
Maybe you could add link to the description?

**Review by nieznanysprawiciel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[`arch-snapshot/arch.md` line 2422 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-OAqsh7f4yN_YQ93fUiy:-OAqsh7f4yN_YQ93fUiz:b-rf1spt) ([raw file](https://github.com/golemfactory/golem-architecture/blob/77fac8d33c07fad295bb2e32a48639bbc56e9e6a/arch-snapshot/arch.md#L2422)):*
> ```Markdown
> 
> The Requestor Agent acts as the source of truth for the IP configuration of
> every VM in the VPN. SDKs simplify this process for users—they specify the
> ```

We don't have interaction with artifacts described like in other parts of document. For example when describing Requestor interaction we don't say that SDKs provides user-friendly abstraction.

But in general I'm ok with omitting this.
This description is good enough

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dopiera and @nieznanysprawiciel)

___
*[`arch-snapshot/arch.md` line 683 at r1](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-O9nruS88LSHz0gEpS09:-OAsoUVv8m5zpSorVsaP:bkgbpju) ([raw file](https://github.com/golemfactory/golem-architecture/blob/a401c0c108ec51f5227081f15c5eec6aee84d8bb/arch-snapshot/arch.md#L683)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

For example outbound-gateway: https://github.com/golemfactory/ya-runtime-outbound-gateway which was used in prototype of VPN routing traffic through golem nodes
</blockquote></details>

I didn't know about this one - added to the list of clients.

Anyway I think after reorganizing the content from this PR your comment has been addressed, no?
___
*[`arch-snapshot/arch.md` line 2374 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-OAqg_nG67ExcGi4uBsM:-OAso4aB-gtmV3AeSmIZ:b-dzquwa) ([raw file](https://github.com/golemfactory/golem-architecture/blob/77fac8d33c07fad295bb2e32a48639bbc56e9e6a/arch-snapshot/arch.md#L2374)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

I forgot to comment earlier: `securely` can be misleading. VPN doesn't encrypt traffic by itself. It relies on networking layer to do it. And currently there is no encryption.
</blockquote></details>

I've added a sentence to the "Data Plane Internals" section to make it clear.
___
*[`arch-snapshot/arch.md` line 2422 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-OAqsh7f4yN_YQ93fUiy:-OAsoHZf98RL70mP-2hT:b2nha9w) ([raw file](https://github.com/golemfactory/golem-architecture/blob/77fac8d33c07fad295bb2e32a48639bbc56e9e6a/arch-snapshot/arch.md#L2422)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

We don't have interaction with artifacts described like in other parts of document. For example when describing Requestor interaction we don't say that SDKs provides user-friendly abstraction.

But in general I'm ok with omitting this.
This description is good enough
</blockquote></details>

ACK
___
*[`arch-snapshot/arch.md` line 2450 at r3](https://reviewable.io/reviews/golemfactory/golem-architecture/114#-OAqhbdA7F0eGtEg44DE:-OAsqrUk58usn6oZJtei:bykgvj0) ([raw file](https://github.com/golemfactory/golem-architecture/blob/77fac8d33c07fad295bb2e32a48639bbc56e9e6a/arch-snapshot/arch.md#L2450)):*
<details><summary><i>Previously, nieznanysprawiciel wrote…</i></summary><blockquote>

> unreliable channels
I changed terminology to transport type.
But I think you can leave it as is.
Maybe you could add link to the description?
</blockquote></details>

Fixed, PTAL.

**Review by nieznanysprawiciel — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/golemfactory/golem-architecture/114)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
